/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface UniswapTestInterface extends ethers.utils.Interface {
  functions: {
    "cocosTokenERC20()": FunctionFragment;
    "getEstimatedETHforDAI(uint256)": FunctionFragment;
    "getPathForERCTokens(address,address)": FunctionFragment;
    "pundiToken()": FunctionFragment;
    "swapCocosToPundix(uint256)": FunctionFragment;
    "swapPundixToWeth(uint256)": FunctionFragment;
    "uniswapRouter()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "cocosTokenERC20",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEstimatedETHforDAI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPathForERCTokens",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "pundiToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapCocosToPundix",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapPundixToWeth",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapRouter",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "cocosTokenERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEstimatedETHforDAI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPathForERCTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pundiToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapCocosToPundix",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapPundixToWeth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapRouter",
    data: BytesLike
  ): Result;

  events: {};
}

export class UniswapTest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: UniswapTestInterface;

  functions: {
    cocosTokenERC20(overrides?: CallOverrides): Promise<[string]>;

    getEstimatedETHforDAI(
      pundiAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    getPathForERCTokens(
      token1: string,
      token2: string,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    pundiToken(overrides?: CallOverrides): Promise<[string]>;

    swapCocosToPundix(
      amountIn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapPundixToWeth(
      amountIn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    uniswapRouter(overrides?: CallOverrides): Promise<[string]>;
  };

  cocosTokenERC20(overrides?: CallOverrides): Promise<string>;

  getEstimatedETHforDAI(
    pundiAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getPathForERCTokens(
    token1: string,
    token2: string,
    overrides?: CallOverrides
  ): Promise<string[]>;

  pundiToken(overrides?: CallOverrides): Promise<string>;

  swapCocosToPundix(
    amountIn: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapPundixToWeth(
    amountIn: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  uniswapRouter(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    cocosTokenERC20(overrides?: CallOverrides): Promise<string>;

    getEstimatedETHforDAI(
      pundiAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getPathForERCTokens(
      token1: string,
      token2: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    pundiToken(overrides?: CallOverrides): Promise<string>;

    swapCocosToPundix(
      amountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    swapPundixToWeth(
      amountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    uniswapRouter(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    cocosTokenERC20(overrides?: CallOverrides): Promise<BigNumber>;

    getEstimatedETHforDAI(
      pundiAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPathForERCTokens(
      token1: string,
      token2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pundiToken(overrides?: CallOverrides): Promise<BigNumber>;

    swapCocosToPundix(
      amountIn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapPundixToWeth(
      amountIn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    uniswapRouter(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    cocosTokenERC20(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getEstimatedETHforDAI(
      pundiAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPathForERCTokens(
      token1: string,
      token2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pundiToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    swapCocosToPundix(
      amountIn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapPundixToWeth(
      amountIn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    uniswapRouter(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
